export const START_SUBMITTING = 'START_SUBMITTING';
export const SUCCESSFUL_SUBMITTING = 'SUCCESSFUL_SUBMITTING';
export const FAILED_SUBMITTING = 'FAILED_SUBMITTING';

export const START_SENDING_CONTACTS = 'START_SENDING_CONTACTS';
export const SUCCESSFUL_SENDING_CONTACTS  = 'SUCCESSFUL_SENDING_CONTACTS';
export const FAILED_SENDING_CONTACTS  = 'FAILED_SENDING_CONTACTS';

export const SET_NOTIFICATION  = 'SET_NOTIFICATION';
export const RESET_NOTIFICATION  = 'RESET_NOTIFICATION';

export const SET_VIDEO_COST = 'SET_VIDEO_COST';
